apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "remediai.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "remediai.labels" . | nindent 4 }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.global.workloadIdentityClientId | quote }}
