from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS_ROOT = ROOT / "apps" / "docs" / "docs"
GENERATED_DIR = DOCS_ROOT / "_generated"


@dataclass(frozen=True)
class SyncTarget:
    source: Path
    output: Path
    sections: tuple[str, ...]


SYNC_TARGETS: tuple[SyncTarget, ...] = (
    SyncTarget(
        source=ROOT / "ARCHITECTURE.md",
        output=GENERATED_DIR / "architecture-overview.mdx",
        sections=(
            "Overview",
            "Component Diagram",
            "Services",
            "Infrastructure",
            "Deployment Model",
            "Observability",
        ),
    ),
    SyncTarget(
        source=ROOT / "ARCHITECTURE.md",
        output=GENERATED_DIR / "architecture-data-flow.mdx",
        sections=("Data Flow",),
    ),
    SyncTarget(
        source=ROOT / "TECH_STACK.md",
        output=GENERATED_DIR / "architecture-tech-stack.mdx",
        sections=(
            "Summary",
            "Python Dependencies (Key)",
            "Frontend Dependencies (Key)",
            "Local Development",
            "Version Pinning Policy",
        ),
    ),
    SyncTarget(
        source=ROOT / "SECURITY_GUARDRAILS.md",
        output=GENERATED_DIR / "security-principles.mdx",
        sections=(
            "Principles",
            "Secret Management",
            "Network Security",
            "Application Security",
            "Responsible Disclosure",
        ),
    ),
    SyncTarget(
        source=ROOT / "SECURITY_GUARDRAILS.md",
        output=GENERATED_DIR / "security-pii-scrubbing.mdx",
        sections=("PII and Data Handling",),
    ),
    SyncTarget(
        source=ROOT / "SECURITY_GUARDRAILS.md",
        output=GENERATED_DIR / "security-identity.mdx",
        sections=("Identity and Access",),
    ),
    SyncTarget(
        source=ROOT / "SECURITY_GUARDRAILS.md",
        output=GENERATED_DIR / "security-audit-log.mdx",
        sections=("Audit Trail",),
    ),
    SyncTarget(
        source=ROOT / "ROADMAP.md",
        output=GENERATED_DIR / "roadmap.mdx",
        sections=("Current Status",),
    ),
    SyncTarget(
        source=ROOT / "CONTRIBUTING.md",
        output=GENERATED_DIR / "contributing-dev-environment.mdx",
        sections=("Development Environment",),
    ),
    SyncTarget(
        source=ROOT / "CONTRIBUTING.md",
        output=GENERATED_DIR / "contributing-branch-conventions.mdx",
        sections=("Branch Conventions", "Commit Messages", "Pull Request Process"),
    ),
)


def extract_section(markdown: str, heading: str) -> str:
    lines = markdown.splitlines()
    start_index: int | None = None
    for index, line in enumerate(lines):
        if line == f"## {heading}":
            start_index = index
            break

    if start_index is None:
        raise ValueError(f"Heading not found: {heading}")

    end_index = len(lines)
    for index in range(start_index + 1, len(lines)):
        if lines[index].startswith("## "):
            end_index = index
            break

    section = "\n".join(lines[start_index:end_index]).strip()
    return f"{section}\n"


def build_generated_content(target: SyncTarget) -> str:
    source_text = target.source.read_text(encoding="utf-8")
    sections = [extract_section(source_text, heading) for heading in target.sections]
    body = "\n\n".join(section.strip() for section in sections).strip()
    body = body.replace(
        "[SECURITY.md](SECURITY.md)",
        "[SECURITY.md](https://github.com/akeesari/remediai/blob/main/SECURITY.md)",
    )
    return (
        "{/* This file is generated by scripts/sync_docs_site.py. Do not edit directly. */}\n\n"
        f"{body}\n"
    )


def main() -> None:
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)

    for target in SYNC_TARGETS:
        target.output.write_text(build_generated_content(target), encoding="utf-8")
        print(f"synced {target.output.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
