apiVersion: v1
kind: Service
metadata:
  name: {{ include "remediai.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "remediai.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.api.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "remediai.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
